_pretrain_net:
  _target_: asparagus.modules.networks.primus.${model.pretrain_net}
  patch_size: ${training.patch_size}
  patch_drop_rate: ${training.mask_ratio}
  patch_embed_size: ${model.patch_embed_size}

_seg_net:
  _target_: asparagus.modules.networks.primus.${model.seg_net}
  patch_size: ${training.patch_size}
  patch_drop_rate: 0.0
  patch_embed_size: ${model.patch_embed_size}

_cls_net:
  _target_: asparagus.modules.networks.primus.${model.cls_net}
  patch_size: ${training.patch_size}
  patch_drop_rate: 0.0
  patch_embed_size: ${model.patch_embed_size}

_plugin_seg_net:
  _target_: asparagus.modules.networks.primus.${model.plugin_seg_net}
  patch_size: ${training.patch_size}
  patch_drop_rate: 0.0
  patch_embed_size: ${model.patch_embed_size}

pretrain_optim: AdamW
pretrain_lr: 3e-4
train_optim: AdamW
train_lr: 3e-4
finetune_optim: AdamW
finetune_lr: 3e-5
patch_embed_size: 8

weight_decay: 5e-2
nesterov: False
momentum: 0.9

min_test_patch_size: ${training.patch_size}
deep_supervision: False # not supported
