# @package _global_
defaults:
  - /default_pretrain
  - /model/resenc_unet_b@model
  - /hardware/1gpu12cpu@hardware
  - _self_

task: PT900_FOMO300K
root: development
stem: pretrain

checkpoint_run_id:

training:
  batch_size: 8
  accumulate_grad_batches: 2
  max_samples: 6_000_000
  warmup_ratio: 0.02

model:
  use_skip_connections: False

logger:
  log_every_n_steps: 10