defaults:
  - core/base@
  - hardware/1gpu40cpu@hardware
  - _self_

task:
checkpoint_run_id:
load_checkpoint_name: last.ckpt
hf_model_id:
root: base
stem: ${checkpoint_run_id}_${load_checkpoint_name}

model:
  net: ${model.cls_net}

lightning:
  data_module: ClsRegDataModule
  lightning_module: LinearProbeModule

data:
  data_path: ${oc.env:ASPARAGUS_DATA}/${task}
  train_split: split_75_15_10
  fold: 0

training:
  warmup_epochs: 0
  max_epochs: 15
  batch_size: 4
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  target_size: [160, 160, 160]
  pretrained_target_size:
  seed: ${random:0,10000000}
  check_val_every_n_epoch: 2
  probing:
    learning_rates: [5e-5, 1e-4, 5e-4, 1e-3, 5e-3, 1e-2, 5e-2, 1e-1]
  accumulate_grad_batches: 2

transforms:
  cpu_tr_transforms: CPU_clsreg_val_test_transforms_crop
  cpu_val_transforms: CPU_clsreg_val_test_transforms_crop
  gpu_tr_transforms: none
  gpu_val_transforms: none
  normalize: True

logger:
  progress_bar: True
  wandb_logging: True
  wandb_entity: ${oc.env:WANDB_ENTITY, "team-asparagus"}
  mlflow_logging: False
  log_every_n_steps: 25
  log_images_every_n_epoch: 9999999
